trigger:
  tags:
    include:
    - '*'

pr: none
pool:
    vmImage: 'ubuntu-latest'
      
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: python -m pip install pipenv
  displayName: 'Install pipenv'

- script: pipenv requirements > requirements.txt
  displayName: 'Create requirements.txt from Pipfile.lock'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: python setup.py bdist_wheel 
  displayName: 'Artifact creation'

- script: python -m pip install --upgrade twine
  displayName: 'Install Twine'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: $(ARTIFACT_FEED)

- script: |
    python -m twine upload --skip-existing -r $(REPOSITORY) --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Publish to PyPi through Twine'
