SUBMISSION_PATH = 'Submissions'
USER_PATH = 'Users'
ORG_PATH = 'Organisations'
ANALYSIS_PATH = 'Analyses'
JOB_INSTANCE_PATH = 'JobInstance'
STATIC_PATH = 'StaticTable'
PROJECT_PATH = 'Projects'
TREE_PATH = 'Tree'
