
FASTQ_UPLOAD_TYPE = 'fastq'
FASTA_UPLOAD_TYPE = 'fasta'

BY_IS_ACTIVE_FLAG = 'by-is-active-flag'
BY_LATEST_DATE = 'by-latest-date'

READ_1 = '1'
READ_2 = '2'
READ_BOTH = '-1'

SEQ_TYPES = [FASTA_UPLOAD_TYPE, FASTQ_UPLOAD_TYPE]
SEQ_FILTERS = [BY_IS_ACTIVE_FLAG, BY_LATEST_DATE]
READS = [READ_1, READ_2, READ_BOTH]
