resources:
  repositories:
    - repository: CLI
      type: github
      name: AusTrakka/austrakka2-cli
      ref: $(Build.SourceBranch)
      endpoint: AusTrakka
    - repository: Pipelines
      type: github
      name: AusTrakka/austrakka-pipelines
      ref: 6809-cli-build-publish # TODO: change this to Development
      endpoint: AusTrakka

trigger:
  - Development
  - UAT
  - master

pr:
  - Development
  - UAT
  - master

variables:
  - template: variables/devops/setup.yml@Pipelines

stages:
  - stage: RunCliTests
    jobs:
      - job: RunCliTests
        steps:
          - template: templates/checkout/cli.yml@Pipelines
          - template: templates/test/unit/cli.yml@Pipelines
