name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          echo "VERSION=$(cat austrakka/__init__.py | grep __version__ | cut -d "=" -f2 | cut -d "\"" -f2)" >> $GITHUB_ENV
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          custom_tag: ${{ env.VERSION }}
          tag_prefix: ''
