name: Check Azure Board issues are linked

on:
  pull_request:
    branches: [ master, Development, UAT ]
    types: [ opened, edited, reopened ]

  workflow_dispatch:

jobs:
  check-ab-link:
    if: ${{ github.actor == 'azure-boards[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: ab-story-validation
        uses: emagers/ab-story-validation-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.AUSTRAKKA_ACTIONS_PAT }}
