name: linting
on: pull_request
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv requirements --dev-only | tee requirements.txt
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint --disable=import-error,too-few-public-methods austrakka test
