name: Auto PR master -> Dev
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create auto PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.AUSTRAKKA_ACTIONS_PAT }}
          source_branch: master
          target_branch: Development
          title: master -> Development
          body: "**Automated pull request: DO NOT add Azure Board links to this body**"