name: Sync setup.py with Pipfile

on:
  push:
    branches: [Development, UAT, master]

jobs:
  setup-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUSTRAKKA_ACTIONS_PAT }}
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv requirements --dev-only | tee requirements.txt
          pip install -r requirements.txt
      - name: Sync setup.py
        run: |
          pipenv-setup sync
      - name: Commit setup.py changes
        run: |
          git config --global user.name 'austrakka-bot'
          git config --global user.email 'austrakka-bot@austrakka.net.au'
          git commit -am "Sync setup.py"
          git push
